### ISSUE TITLE
How to add it to nvchad

### ISSUE THREAD

**Issue by ayush-india** [jcdickinson/wpm.nvim#1]
I cannot understand how can i add this pligins featrues to nvchad
It uses it own plugin as a status bar https://github.com/NvChad/ui
repo: https://github.com/Nvchad/Nvchad

**Comment by jcdickinson** [comment]
It looks like their website has documentation on how to customize their UI: https://nvchad.com/config/Walkthrough

1. You will need to load the plugin: https://nvchad.com/config/plugins
2. Then add it to the statusline: https://nvchad.com/config/nvchad_ui#statusline--tabufline

I'm not a NvChad user, but it looks like they have an active Discord server where you can find help: https://discord.gg/gADmkJb9Fb
