### ISSUE TITLE
Display 'nil' in lualine

### ISSUE THREAD

**Issue by guxuerui** [jcdickinson/wpm.nvim#4]
I use Packer

After downloading `wpm.nvim`, it shows `nil` when used in `lualine`.

config:

```lua
  sections = {
	lualine_a = {
		"mode",
	},
	lualine_b = { "branch", "diff", "diagnostics" },
	-- show the current filename and session name,
    lualine_c = { "filename", require('auto-session-library').current_session_name },
	lualine_x = { "encoding", "fileformat", "filetype", require("wpm").wpm, require("wpm").historic_graph },
	lualine_y = { "progress" },
	lualine_z = { "location" },
     },
```

Like this:

![image](https://user-images.githubusercontent.com/23629097/216935022-9e99c66b-417e-4d87-adad-38a2a29ef3e2.png)

What could be the reason?

**Comment by jcdickinson** [comment]
That's strange. What does `:lua vim.prettyprint(require("wpm").wpm` show?

**Comment by guxuerui** [comment]
> im.prettyprint(require("wpm").wpm

NO. I got this error

![image](https://user-images.githubusercontent.com/23629097/217132432-33194e6c-b5e6-48de-a9a7-65ee4cdc8e20.png)

**Comment by guxuerui** [comment]
> That's strange. What does `:lua vim.prettyprint(require("wpm").wpm)` show?

I migrated  from Packer.nvim to Lazy.nvim today, and the problem have solved...!

So I guess there might be something wrong with Packer.nvim

Anyway, thank you for your replay!

**Comment by jcdickinson** [comment]
Hmmm, I wonder if I have the packer.nvim example wrong. Glad it worked out for you.

**Comment by jcdickinson** [comment]
Closing in favor of #5.
